# -*- coding: utf-8 -*-
"""Sinistro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dq8PeXY0OGaLisIpPWU8g0qwotcMu554
"""

import pandas as pd
import numpy as np
import datetime

# Recarregar o DataFrame original
df = pd.read_excel("SINISTRO 2026.xlsx")
print("DataFrame recarregado do arquivo SINISTRO 2026.xlsx.")

# 2. Redefinir e aplicar a função remover_colunas
def remover_colunas(df):
  coluna_remover = ["ano_sinistro", "mes_sinistro", "dia_sinistro", "ano_mes_sinistro", "dia_da_semana", "turno", "tipo_local", "cod_ibge", "regiao_administrativa", "administracao", "conservacao", "circunscricao", "qtd_gravidade_ileso", "tp_sinistro_atropelamento", "tp_sinistro_colisao_frontal", "tp_sinistro_colisao_traseira", "tp_sinistro_colisao_lateral", "tp_sinistro_colisao_transversal", "tp_sinistro_colisao_outros", "tp_sinistro_choque", "tp_sinistro_capotamento", "tp_sinistro_engavetamento", "tp_sinistro_tombamento", "tp_sinistro_outros", "tp_sinistro_nao_disponivel"]
  df = df.drop(columns=coluna_remover, errors='ignore')
  return df

df = remover_colunas(df)
print("Colunas removidas com sucesso.")

# 3. Reaplicar a agregação de colunas
if 'qtd_veic_outros' in df.columns and 'qtd_veic_nao_disponivel' in df.columns:
    df['qtd_veic_outros_não_dispo'] = df['qtd_veic_outros'] + df['qtd_veic_nao_disponivel']
    df = df.drop(columns=['qtd_veic_outros', 'qtd_veic_nao_disponivel'])
    print("Colunas 'qtd_veic_outros' e 'qtd_veic_nao_disponivel' somadas em 'qtd_veic_outros_não_dispo' e removidas.")
else:
    print("Uma ou ambas as colunas ('qtd_veic_outros', 'qtd_veic_nao_disponivel') não foram encontradas para agregação.")

# 4. Reaplicar tratamento de valores numéricos implausíveis
# Tratar valores negativos em 'numero_logradouro'
if 'numero_logradouro' in df.columns:
    original_negative_count = (df['numero_logradouro'] < 0).sum()
    df.loc[df['numero_logradouro'] < 0, 'numero_logradouro'] = np.nan
    if original_negative_count > 0:
        print(f"Convertidos {original_negative_count} valores negativos em 'numero_logradouro' para NaN.")
    else:
        print("Não foram encontrados valores negativos em 'numero_logradouro'.")

# Tratar 0.0 em 'latitude' e 'longitude'
for col in ['latitude', 'longitude']:
    if col in df.columns:
        original_zero_count = (df[col] == 0.0).sum()
        df.loc[df[col] == 0.0, col] = np.nan
        if original_zero_count > 0:
            print(f"Convertidos {original_zero_count} valores 0.0 em '{col}' para NaN.")
        else:
            print(f"Não foram encontrados valores 0.0 em '{col}'.")

print("Valores numéricos implausíveis tratados (negativos e 0.0).")

from google.colab import drive
drive.mount('/content/drive')

if 'hora_sinistro' in df.columns:
    def convert_to_time_robust(value):
        if pd.isna(value):
            return pd.NaT
        if isinstance(value, datetime.time):
            return value
        try:

            return pd.to_datetime(str(value)).time()
        except:

            return pd.NaT

    original_nan_count_hs = df['hora_sinistro'].isnull().sum()
    df['hora_sinistro'] = df['hora_sinistro'].apply(convert_to_time_robust)
    new_nan_count_hs = df['hora_sinistro'].isnull().sum()

    print(f"Coluna 'hora_sinistro' convertida para o tipo de tempo. NaNs originais: {original_nan_count_hs}, NaNs após conversão: {new_nan_count_hs}.")
    display(df[['hora_sinistro']].head())
    display(df['hora_sinistro'].value_counts(dropna=False).head())
else:
    print("Coluna 'hora_sinistro' não encontrada para conversão.")

qtd_cols = [col for col in df.columns if col.startswith('qtd_')]

filled_count = 0
for col in qtd_cols:
    if df[col].isnull().any():
        initial_nulls = df[col].isnull().sum()
        df[col] = df[col].fillna(0)
        filled_count += initial_nulls
        print(f"Preenchidos {initial_nulls} valores NaN na coluna '{col}' com 0.")

if filled_count == 0:
    print("Não há valores NaN nas colunas 'qtd_' para preencher com 0.")
else:
    print(f"Total de {filled_count} valores NaN preenchidos com 0 nas colunas 'qtd_'.")

missing_values_reloaded = df.isnull().sum()
missing_percentage_reloaded = (df.isnull().sum() / len(df)) * 100

missing_info_reloaded = pd.DataFrame({
    'Missing Values': missing_values_reloaded,
    'Percentage': missing_percentage_reloaded
})

missing_info_reloaded = missing_info_reloaded[missing_info_reloaded['Missing Values'] > 0].sort_values(by='Missing Values', ascending=False)

if not missing_info_reloaded.empty:
    print("Colunas com Valores Ausentes (após recarregamento e limpeza inicial):")
    display(missing_info_reloaded)
else:
    print("Não há valores ausentes restantes no DataFrame.")

# Salvar o DataFrame em um arquivo CSV
df.to_csv('SINISTRO_limpo.csv', index=False)
print("DataFrame salvo como 'SINISTRO_limpo.csv' com sucesso!")

from google.colab import files

files.download('SINISTRO_limpo.csv')

import pandas as pd
from google.colab import files

# Carregar o CSV limpo de volta para um DataFrame
df_cleaned_csv = pd.read_csv('SINISTRO_limpo.csv')

# Salvar o DataFrame como um arquivo Excel
df_cleaned_csv.to_excel('SINISTRO_limpo.xlsx', index=False)
print("DataFrame salvo como 'SINISTRO_limpo.xlsx' com sucesso!")

# Baixar o arquivo Excel
files.download('SINISTRO_limpo.xlsx')